server:
  port: 4040
  
  
spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017  
      
      
  mail:
    host: smtp.office365.com
    password: Kumar28031999
    port: 587
    properties:
      mail:
        smtp:
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 5000  
          auth: true
          starttls:
            enable: true
        store:  
          protocol: smtp
    username: kumarjeba928@outlook.com
      