server:
  port: 4040
  
  
spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017  
      
      
  mail:
    host: smtp.office365.com
    password: Mangalam@123
    port: 587
    properties:
      mail:
        smtp:
         
          auth: true
          starttls:
            enable: true
          
    protocol: smtp
    username: kumar.v@avasoft.com
      