server:
  port: 4040
  
  
spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017  
      
      
  mail:
    host: smtp.gmail.com
    password: wayizsozmbxhqjpv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    username: jebakumar928@gmail.com
      