server:
  port: 4041
  
  
spring:
  data:
    mongodb:
      host: localhost
      database: MyRequest
      port: 27017  
      
      
  mail:
    host: smtp.outlook.com
    password: kumar28031999
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          protocol: smtp
    username: harishkanna987@outlook.com
      